modules/auth/store.js

Added logout endpoint option!
This code is example for case of [Laravel passport](https://laravel.com/docs/5.4/passport) (Password Grant Tokens)
```php
// Endpoint is /oauth/tokens/eyJ0eXAiOiJKV1Qi.......
this.logout({
endpoint: 'oauth/tokens',
appendToken: true
})
```

Add logout endpoint option

---

modules/axios/plugin.js

export default axios instance so that user can do some things with it. eg https://github.com/nuxt/express/blob/master/protected-ssr-api.md#create-middlewaressr-cookiejs
```js
import axios from '../.nuxt-modules/modules/nuxt_axios_plugin'
export default function({isServer, req}) {
if (isServer) {
axios.defaults.headers.common.cookie = req.headers.cookie
}
}
```

export default axios instance

---

modules/bootstrap-vue/index.js

ReferenceError: options is not defined
at Module.nuxtBootstrapVue (/home/rich/Projects/da-lee/node_modules/@nuxtjs/bootstrap-vue/index.js:10:63)
at /home/rich/Projects/da-lee/node_modules/nuxt/dist/nuxt.js:1784:29
at Promise (<anonymous>)
at F (/home/rich/Projects/da-lee/node_modules/core-js/library/modules/_export.js:35:28)
at Module.addModule (/home/rich/Projects/da-lee/node_modules/nuxt/dist/nuxt.js:1783:14)
at /home/rich/Projects/da-lee/node_modules/nuxt/dist/nuxt.js:198:14
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:169:7)
at Function.Module.runMain (module.js:607:11)
at startup (bootstrap_node.js:158:16)
at bootstrap_node.js:575:3
error Command failed with exit code 1.

Fix options reference and moduleOptions typo

---

modules/axios/README.md
modules/axios/index.js
modules/axios/plugin.js

Idea taken from this package: https://github.com/andykingking/axios-debug
When you set `debug: true` all requests and responses are printed. I looked at the other modules and it seems at the moment there is no default implementation for logging, so I am directly calling `console.info`.
btw, I thought about checking for env debug but I think this is much to verbose so a separate debug option is reasonable

[axios] added debug option to log all requests & responses

---

modules/google-analytics/index.js
modules/google-analytics/plugin.js

This change add possibility to set custom fields for GA. Eg. expId and expVar.
Plugin checks ```to.meta.analytics``` and if it is present sets GA fields.
It is not yet working for the initial request because ```to.meta``` is undefined.

Setting custom fields for google analytics

---

modules/axios/index.js

My dev setup is a bit strange with people locally connecting from http but remote with https through an nginx proxy. Unfortunately remote access wasnt working as for a relative url with a missing scheme part URL will use the scheme part of it's baseURL `http://${host}:${port}` and thus will always be set to http.
This caused people connecting over https from remote to receive 'blocked: mixed-content` errors.
In commit 19b8453473e205719b2ef81767a1ad6771cf4766 it was mentioned that e.g. the url `//google.com` was fixed, but I guess that it was only fixed by forcing to use http. A scheme-less url should be valid in (most/all?) browsers so only for SRR a scheme should be added, not in the browser. For reference see this [question](https://stackoverflow.com/questions/4831741/can-i-change-all-my …

Fix for scheme-less baseURL's

---

modules/axios/README.md

Called wrong function 'setToken'

Typo in the setHeader example

---

modules/axios/package.json
modules/axios/plugin.js

Fix for issue #39 as discussed there
Also added chalk as dependency because otherwise if you run `yarn link` the axios plugin cant find it.

Fix for 39: When proxyHeaders dont copy host header

---

modules/meta/index.js

**Issue** : 
The generated `apple-touch-icon` meta uses the 16*16 px favicon from the manifest.
**Fix** : 
Creating an `applefavicon` key in the `options` object with the correct link.

Fix apple-touch-icon meta link

---

modules/google-tag-manager/index.js

This is a sane default and makes GTM work out of the box. It also reflects README.md, which already suggests that `layer` is set to `dataLayer` (which is a bit of a gotcha if you aren't browsing the source).

FIX: google-tag-manager default 'layer' should be set to 'dataLayer'

---

modules/axios/README.md
modules/axios/index.js
modules/axios/plugin.js

In relation to issue here: https://github.com/nuxt-community/modules/issues/73
It's be very helpful to simply disable this response interceptor that handles errors. On SSR I'd like to be able to try and refresh a JWT token before displaying a 403 page or whatever custom logic.
I can add documentation if you think this is OK?

Optionally disable error handling

---

modules/markdownit/README.md

While copying the configuration object of the readme out of [npm](https://www.npmjs.com/package/@nuxtjs/markdownit) there was a wrong indentation. Since most of the example included two spaces as indentation i used it there too.

Fix indentation of readme

---

modules/workbox/index.js

Hey there,
The Workbox module for nuxt is great at providing a quick and easy "offline" version of a nuxt application, but I spotted two issues.
**1 - Server-Bundle.json being downloaded**
As the globPattern matches every .json files, the precache would retrieve and store server-bundle.json that is not required on client side.
**2 - Routes order is wrong**
The routes for runtime caching are being generated in the wrong order. If you goes offline, it doesn't change anything, as the "networkFirst" strategy will fail right away they move on to cache. But if you test your app with poor network conditions (or network throttling) you can see that even the precached files at being served with the second route, which uses the networkFirst strategy.
Changing the order of the two generated routes …

Workbox Precaching and strategies optimisation

---

modules/axios/README.md
modules/axios/plugin.js

This is useful option for adding custom headers for all requests based on the state of the store or some other values.
Can be also used for handling authorizations headers instead of setToken method which cannot be used on the server side in the current implementation.

- option for setting custom request interceptor

---

modules/axios/package.json
modules/axios/plugin.js

This is a bug fix for function serialization when using nuxt as middleware with babel
https://github.com/nuxt-community/modules/issues/106

- nuxt/axios - bug fix, function serialization with babel

---

modules/workbox/plugin.js

ServiceWorker check was always resolving true in browsers that didn't support the feature

Fix for serviceworker check

---

modules/browserconfig/index.js

Make browserconfig module use `srcDir` instead of `rootDir` for consistency with core & other modules.

Browserconfig path fix

---

modules/meta/index.js

as shown in https://nuxtjs.org/api/configuration-head/
using `property` attribute produces multiple duplicated meta tags

[meta] use `name` instead of `property` in og tags

---

modules/yandex-metrika/plugin.js

The current yandex-metrika plugin is completely broken, I don't know how it landed in the repository in this shape. Consider the current source code: <https://github.com/nuxt-community/modules/blob/72f0982d6fe85b191941ce3b59f4f909fb355c2e/modules/yandex-metrika/plugin.js>.
In the following code, `w` and `c` are undefined, it will never work:
```js
try {
(w[c] = w[c] || []).push(function() {
window['yaCounter<%= options.id %>'] = new Ya.Metrika(<%= JSON.stringify(options) %>);
})(document, window, 'yandex_metrika_callbacks');
} catch (e) {}
```
This was supposed to be wrapped in `(function (d, w, c) {` (hence the corresponding parameters) but that was lost somehow.
Then, this condition:
```js
if (!window['Ya'] || window['yaCounter46006413']) {
console.warn('Yandex metrika is not …
```

yandex-metrika: fix undefined vars, prevent race condition

---

modules/yandex-metrika/plugin.js

This is the second iteration of Yandex.Metrika fixes after #143:
- Fix `ReferenceError` coming from inaccurate use of function arguments `({app: { router }})` and variable reference `app.router`.
- Remove `try/catch` block that silences everything (including the error above) for no apparent reason.
- Fix duplicate metrika hit sent for the initial vue-router navigation.
- Send referer data along with the hit (in accordance with https://yandex.com/support/metrica/code/ajax-flash.html).

Fix yandex-metrika ReferenceError and duplicate hits

---

packages/google-tag-manager/index.js
packages/google-tag-manager/package.json

lodash package is so Big! 
it shouldn't be used easily in such a small module.
in my Nuxt.js project, lodash.js file used by `@nuxtjs/google-tag-manager` was the biggest file of all js files...
so i removed lodash dependency.

[google-tag-manager] removed lodash dependency

---

packages/bootstrap-vue/package.json

Released: 2017-11-05
https://bootstrap-vue.js.org/docs/misc/changelog
(New version seems to work fine)

Bump version of bootstrap-vue to 1.0.0

---

packages/markdownit/README.md

Hello.
Maybe, the first argument of markdown-it-container is mandatory.
ref: https://github.com/markdown-it/markdown-it-container

Change README for markdown-it-container

---

packages/google-tag-manager/plugin.js

By naming the push event it allows users to trigger GTM tags based on each route change such as integrating Google Analytics via Google Tag Manager.
Without this, there is no way to trigger any actions within GTM based on a route change within a Nuxt app.
[Tag Manager Docs on pushing Events](https://developers.google.com/tag-manager/devguide#events)

Add dataLayer Event property

---

packages/markdownit/index.js

check if vueLoader.options.loaders exists and create it if it doesn't. Object.assign would also be an option.
this addresses issue #207 
I guess this also has something to do with issue #203
I should note, the current module works fine with nuxt v1

check if vueLoader.options.loaders exists

---

packages/google-tag-manager/README.md
packages/google-tag-manager/index.js

This PR allows GTM ID to be function returning String or Promise, as shown in readme.md examples

feat(google-tag-manager): Allow GTM ID to be function

---

packages/bulma/README.md

postcss-cssnext is depreciated, update instructions to use postcss-preset-env

update instructions to use postcss-preset-env

---

packages/google-tag-manager/index.js

Hi,
The README tells that google-tag-manager is not run in dev mode but it doesn't seems to work.
This PR should fix it.
Thanks !

[google-tag-manager] Do not include when run in dev mode

---

packages/google-tag-manager/plugin.js

This fixes the incorrect variable reporting. Without this, if you inspect the raw variables in GTM preview mode, you'll see that `_url`, `Page URL` and `Page Path` are incorrectly reported. It reports the previous page, because when `router.afterEach` fires, I presume the internal browser data was not updated yet.

Fixes wrong URL reporting

---

packages/vuetify/README.md
packages/vuetify/index.js
packages/vuetify/package.json
packages/vuetify/plugin.js

`{ treeShake: true }` in module options will utilise [vuetify-loader](https://github.com/vuetifyjs/vuetify-loader) to
enable automatic tree-shaking with webpack.

feat(vuetify): add tree-shaking option

---

packages/ngrok/index.js

The error returned by ngrok is an object with an error message contained within. 
Example error object:
```js
{ 
error_code: 103,
status_code: 502,
msg: 'failed to start tunnel',
details: { 
err: 'Only paid plans may bind custom subdomains.\nFailed to bind the custom subdomain \'foobar\' for the account \'samturrell\'.\nThis account is on the \'Free\' plan.\n\nUpgrade to a paid plan at: https://dashboard.ngrok.com/billing/plan\n\nERR_NGROK_313\n' 
} 
}
```
Adjusted the Nuxt error handler to reference this message rather than the entire object so that the feedback in the console is more useful than `[nuxt][ngrok] [object Object]`

Updates error handler to reference ngrok error

---

packages/toast/README.md
packages/toast/index.js
packages/toast/plugin.js

Trying to add the ability to register custom toasts from nuxt config.
It would look like this:
```  
toast: {
position: 'bottom-right',
register: [
{
name: 'test',
message: (payload) => {
if(!payload.message) return "Default message"
return payload.message
},
options: {
type : 'success',
duration: 3000,
}
},
]
},
```
Usage:
```
this.$toast.global.test()
this.$toast.global.test({ message: "Custom message here" } )
```

feat(toast): add ability to register custom toasts

---

README.md

There was a link to a firebase package which does not exist.

Fix Broken Link in README.md

---

packages/toast/index.d.ts
packages/toast/package.json

Hello,
I have add `index.d.ts` to toast module for allow use `this.$toast` in typescript.
Note: This PR is in draft because need this PR : https://github.com/shakee93/vue-toasted/pull/119
Thanks.

frat(toast): add typescript definitions

---

packages/google-tag-manager/plugin.js

The condition for initializing page tracking doesn't work properly:
```js
!this.options.respectDoNotTrack && this.options.pageTracking && !this.hasDNT()
```
Using `&&` everywhere means that setting `respectDoNotTrack` to true will prevent the entire condition from ever resolving to `true`, even if the user does not have the "do not track" setting to `true`.
Setting `respectDoNotTrack` to `true` means that the condition will only resolve to `true` if the user disables "dot not track" (and thus means that the user's "do not track" setting is then respected)

fix(google-tag-manager): fix respectDoNotTrack

---

packages/markdownit/README.md

Hi, I worked with markdown-it-container and it's mandatory containerName variable is harder to handle in application if we want to give a custom classes to divs. I found that with markdown-it-div plugin it's working out-of the box so I recommend to change it in README, cause it's not even listed in makdownit example plugins section.

docs(markdownit): suggest using `markdown-it-div`

---

packages/bulma/README.md

config in README is now the same as the config when creating a Nuxtjs+Bulma app with `create-nuxt-app`
- postcss config changed
- Run ESLint on save is not needed anymore, as `@nuxtjs/eslint-module` exists

docs(bulma): update build config

---

packages/google-tag-manager/README.md
packages/google-tag-manager/index.js

- Fixes #263 by adding a <noscript> fallback (as suggested here: https://developers.google.com/tag-manager/devguide)
- Adds example of all default options in Readme.md

feat(google-tag-manager): add `<noscript>` fallback (#263)

---

packages/google-tag-manager/README.md
packages/google-tag-manager/index.js
packages/google-tag-manager/plugin.js

This PR adds the `pageViewEventName` option to allow changing the default `nuxtRoute` event name used for page views. 
`nuxtRoute` is very specific and not really friendly to marketing teams, plus the only way to know the event name is to read the code.

feat(google-tag-manager): add pageViewEventName option

---

packages/yandex-metrika/index.js

Without explicitly specifying true in the async attribute, Nuxt did not generate it when building the project. Also added preload for the script.

fix(yandex-metrika): preload and async

---

packages/google-tag-manager/index.js

The`noscript` tag gets included with the content sanitized. 
I'm pretty sure that's not the intended behavior for the content :)

fix(google-tag-manager): fixed noscript content sanitization

---

packages/toast/index.d.ts

`$toast` is [injected](https://github.com/nuxt-community/modules/blob/master/packages/toast/plugin.js#L14) into the application by the `inject` function, it can be used from Vuex as well as Vue components.
However, since it was not represented in the `.d.ts` file, I added a type definition.

feat(toast): add `$toast` type definition to vuex context and application options

---

packages/markdownit/index.js

Options are mutated by plugin creation so er have to clone it...

fix(markdownit): prevent mutating options (fixes #216)

---

packages/markdownit/plugin.js

It would be nice if  plugins could be exported as default and not only with module.export = ...

fix(markdownit): intropDefault for plugin imports

---

packages/bulma/index.js

When working with third party stylesheets it's a common practice to add the third party stylesheet before of our custom stylesheet, so we can override the lib style rules.
But this module is inserting `bulma` in the end of css options in Nuxt config, this means that bulma css will be inserted after stylesheets defined in `css` option in `nuxt.config.js` and we cannot override the rules without a high priority selector or using `!important` :sweat:

fix(bulma): import order of the stylesheet

---

packages/markdownit/plugin.js

The MarkdownIt constructor did not take the 'preset' configuration value into account. The preset value should be the first parameter in the constructor.
This PR will take the preset and put it there.

fix(markdownit): `preset` configuration value was ignored

---

packages/google-tag-manager/README.md
packages/google-tag-manager/plugin.js

I am trying to integrate [Google Analytics ecommerce](https://support.google.com/tagmanager/answer/6107169) using @nuxt/google-tag-manager.
The problem I am facing is that in the documentation for ecommerce tracking, I am supposed to push some information to the dataLayer, with no event attached. The code in the plugin only has one method to push stuff to the dataLayer, `pushEvent`, but this method requires an event, and fails to add the data to the dataLayer, because of the missing event attribute.
I added a new method `pushData` for this purpose, and added a reference to it in README.md.

feat(google-tag-manager): add pushData method

---

packages/google-tag-manager/README.md
packages/google-tag-manager/index.js

To improve loading speeds for the application over tracking from GTM resources, it is better to use the defer attribute over the async attribute.  (see https://flaviocopes.com/javascript-async-defer/)
adding option for "scriptDefer" to the module.  But also leaving it default disabled, so that the behavior does not change unexpectedly for users of the module.
This is something we've wanted for ourselves.

adding scriptDefer option to the google-tag-manager plugin

---

packages/google-tag-manager/README.md
packages/google-tag-manager/index.js
packages/google-tag-manager/package.json
packages/google-tag-manager/plugin.js

Google Tag Manger initialisation.
It was not possible prevent auto activate GTM. 
Now there are two new options in module settings: 
- `autoInitOnClientSide` - Send GTM event automatically. Also it is inserting GTM script and noscript elements, if there aren't presetted on server side.
- `presetScriptsOnServerSide` - It is inserting GTM script on server side. It can be blocked with value false.
I also updated README.md file for these new options.
This can be very useful for implementing GDPR and other user scenarios.

Update Google Tag Manager package for initialisation flow

---

packages/yandex-metrika/README.md
packages/yandex-metrika/index.js
packages/yandex-metrika/plugin.js

Yandex metrics released a new version of the code (https://yandex.ru/blog/metrika/novyy-kod-v-nastroykakh-schetchika).
> The hit (url, [title [, referer [, params]]]) signature is outdated. It's supported for backward compatibility, but may be deprecated at any time. We strongly discourage using it. (https://yandex.ru/support/metrica/objects/hit.html)
New Code Initialization Information https://yandex.ru/support/metrica/code/counter-initialize.html.

feat(yandex-metrika): use new version of yandex metrics code

---

packages/yandex-metrika/README.md
packages/yandex-metrika/index.js

PR is pretty self-explanatory. It adds option to specify config in a separate key rather than in module declaration.
Before
---
```js
{
modules: [
[
'@nuxtjs/yandex-metrika',
{
id: 'XXXXXX',
},
],
]
}
```
After
---
```js
{
modules: ['@nuxtjs/yandex-metrika'],
yandexMetrika: {
id: 'XXXXXX',
},
}
```

feat(yandex-metrika): support `yandexMetrika` option

---

packages/yandex-metrika/README.md
packages/yandex-metrika/index.js
packages/yandex-metrika/plugin.js

1. Add runtime config support for yandex-metrika (pre-2.13 compatible).
2. General plugin refactoring, fix metrika `init` call sending all plugin options to Yandex.

feat(yandex-metrika): support runtime config
