modules/browserconfig/README.md
modules/browserconfig/index.js
modules/google-tag-manager/README.md
modules/google-tag-manager/index.js

* prefer local variables
* fix: used the the data2xml module wrong
* update: documentation
* update: `browserconfig.xml` is more common file name
* update: move default constant out of export scope

Fix new modules

---

modules/google-tag-manager/index.js
modules/google-tag-manager/plugin.js

#17 Edits relating to the Lodash template syntax and passing of deep copied options to the plugin during build.

Google Tag Manager - Lodash Syntax and Options

---

modules/axios/README.md
modules/axios/plugin.js

Ability to set common headers and updated readme. see issue https://github.com/nuxt-community/modules/issues/56

Axios setHeader helper

---

README.md
modules/sitemap/CHANGELOG.md
modules/sitemap/README.md
modules/sitemap/index.js
modules/sitemap/package.json

Add module to easily generate a sitemap.xml

Add sitemap module

---

modules/axios/README.md
modules/axios/plugin.js

also it will make intentions more clear

removed axios mixin methods, because $delete is overlapping vue's $delete

---

modules/sitemap/index.js

Since the new Nuxt RC, `this.nuxt.routes` does not exist anymore... 😿 
So we have to init `staticroutes` from `this.extendRoutes()`, instead of `this.extendBuild()`, and to filter routes with `:` or `*` patterns

fix(sitemap): nuxt rc compability

---

modules/axios/README.md

Simplified description to be more concise.
I'd like to include examples on proxy url changing based on environment. How would this look like?

Dynamic API Backend description update

---

README.md
modules/dotenv/README.me

Add dotenv module

---

modules/plugin-utils/README.md
modules/plugin-utils/index.js
modules/plugin-utils/logging.js
modules/plugin-utils/package.json

Finally had some time to add the plugin-utils module as discussed in #52.
Hope you approve the implementation, if not let me know :smile:

added plugin-utils module

---

README.md

@pi0 Is it appropriate to add `plugin-utils` ?

chore: add plugin-utils into readme

---

packages/ngrok/index.js
packages/ngrok/package.json

fix(ngrok): Use correct options

---

packages/vuetify/index.js

- update default materialIcons to be the same as README (default: true)
- minor change material icons href

Update vuetify module

---

packages/markdownit/README.md
packages/markdownit/index.js
packages/markdownit/plugin.js

improve https://github.com/nuxt/nuxt.js/issues/2238

feat: inject $md to app and vue instance

---

packages/firebase/plugin.js

The $firebase variable has firestore() function.
like this
```js
asyncData({app}){
app.$firebase.firestore().get(...)...
}
```

support firestore

---

packages/vuetify/package.json

The v1 alpha release of Vuetify provide few more bug fixes & features.

Bump up vuetify version

---

packages/yandex-metrika/README.md
packages/yandex-metrika/index.js

For those countries where the domain is blocked

Add support use cdn

---

packages/ngrok/index.js

Resolves https://github.com/nuxt/nuxt.js/issues/4317

Fixing missing return

---

packages/localtunnel/README.md
packages/localtunnel/index.js

https://github.com/localtunnel/localtunnel/blob/master/lib/Tunnel.js#L17

Localtunnel: change localtunnel server option

---

packages/yandex-metrika/index.js

Bad value true for attribute async on element script.

fix html validate error

---

packages/google-tag-manager/index.js
packages/google-tag-manager/plugin.js

Hello I tried to implement a option to disable GTM according to DNT
please feel free to comment

feature(google-tag-manager): option to respect DNT header

---

packages/google-tag-manager/plugin.js

@pi0 I made a grave mistake on last PR https://github.com/nuxt-community/modules/pull/261
return cannot be called this way in this template
I have fixed this and also refactored the code a bit
sorry for the mistake and also please comment if this code style is ok

fix(google-tag-manager): fix broken syntax

---

packages/google-tag-manager/index.js

i removed the unexpected character.

fix(google-tag-manager): fixed syntax error

---

packages/bulma/package.json

Please take action to support Bulma [v0.9.0](https://github.com/jgthms/bulma/releases/tag/0.9.0) in @nuxt/bulma. This version has some really useful updates.

feat(bulma): update to v0.9.0 

---

packages/yandex-metrika/index.js
packages/yandex-metrika/plugin.js

I'm fixed loading code of yandex metrika. 
Error at issue [#364](https://github.com/nuxt-community/modules/issues/364) and [#362](https://github.com/nuxt-community/modules/issues/362)

feat(yandex-metrika): update loading script
